### PR TITLE
Sprint #4 - Pull Request to Main

### PR DESCRIPTION
**Pull request by beamb**
Hi!

Here's the virtually final version of our extension 🥳

In this last sprint, we've implemented feedback from our second usability test, fixed bugs and styling, and finally scheduled interruptions! Unfortunately, interruptions as originally designed were impossible - we had to settle for browser alerts, prompting the user to open the extension and practice. Another unfortunate limitation is that the new tab listener is only triggered when a tab is loaded or re-loaded. That is, a quick switch between tabs will not update the interruption countdown. Any ideas or suggestions are welcome - although this is very Chrome specific (using [chrome.tabs](https://developer.chrome.com/docs/extensions/reference/tabs/)).

We have not yet successfully stored user progress in Firestore. We will try to finalise this before the exam.

Thanks and happy holidays!!
Group 3

### CODE REVIEW

**Review by madsnedergaard — APPROVED** [review]
Nice, don't have much to add here - will approve so you can proceed :)

Might be worth fixing these errors, at least the "9 of undefined" made the extension crash on me. It happened when I selected a language, think it was Java :)

image

**Comment by beamb** [comment]
Thank you @madsnedergaard ! 

> Might be worth fixing these errors, at least the "9 of undefined" made the extension crash on me. It happened when I selected a language, think it was Java :)

Seems to me like a problem from background.html :-/ Is it possible to expand the error and see which line of code is causing issues? I remember having that error once in the past - with 17 instead of 9 - but it simply disappeared. There's no 9 nor 17 in the code and I even checked your stored intervals and none are set to 9...

**Comment by beamb** [comment]
On the other hand, we're now also storing user progress in the database! :-) Users aren't asked the same question more than once in the same sitting and after answering a question correctly three times, it's considered learnt and no longer asked. There are some limitations to this as we only have 20 possible quiz questions per language...

**Comment by beamb** [comment]
@madsnedergaard 

We've attempted a fix. No more errors on our end. What about yours? 🤓

**Comment by madsnedergaard** [comment]
> We've attempted a fix. No more errors on our end. What about yours? 🤓

Can't reproduce the bug now! 👌

**Pull request merged**
